### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by laddaland** [cs2103aug2015-f09-1j/main#1]
post all the User Story that you can think of and the User Story last time we discuss here

**Comment by NoobCak3** [comment]
no

From: laddaland 
Sent: Thursday, September 3, 2015 4:32 PM
To: cs2103aug2015-f09-1j/Software_Engineering 
Subject: [Software_Engineering] Our User Story (#1)

post all the User Story that you can think of and the User Story last time we discuss here

**Comment by a0134109** [comment]
Hello testing one two three

**Comment by laddaland** [comment]
can't see "Hello testing one two three"

**Comment by a0134109** [comment]
A user should be able to set Reminders or Alarms for his/her schedule

**Comment by laddaland** [comment]
i not sure whether need to follow the format  like "As a user I can find upcoming tasks, so that I can decide what needs to be done soon."

**Comment by laddaland** [comment]
but if we do it this way, it will be easier to search for it after long discussion

**Comment by a0134109** [comment]
As a user I can categorise or colour code my schedule so that I can be more organized and tidy

**Comment by a0134109** [comment]
As a user I can add description or subtask so that I can remind myself what are the task to complete

**Comment by laddaland** [comment]
As a user i can adjust the reminder time (5 min, 15 min ) before event happen

**Comment by laddaland** [comment]
As a user I can categories my task into different lvl so that i can differentiate all the task.

**Comment by laddaland** [comment]
As a user I can read my task deadline in days, weeks or month, so that have rough idea how much is the workload.

**Comment by laddaland** [comment]
As a user I can read the history of add, delete and accomplished task so that I can know what task i have done on certain date as a history.

**Comment by laddaland** [comment]
As a user I can reschedule a same task on different date so that i don't have to create another new task if there is a need to reschedule it.

**Comment by laddaland** [comment]
As a user I can delete a task if the task is cancelled.

**Comment by laddaland** [comment]
As a user I can add in a task with its criteria in one line of command in certain format so that it can fasten the process of adding task.

**Comment by laddaland** [comment]
As a user I can edit the detail of task anytime.

**Comment by 13307130498** [comment]
As a user I want to add tasks without date so that I could finish it whenever I've got time.

**Comment by 13307130498** [comment]
As a user I want to share my tasks with my partners.

**Comment by laddaland** [comment]
As a user I can categories my task into group of category, so that it can be view in different categories

**Comment by 13307130498** [comment]
As a user I want to delete a task when I don't need to finish it.

**Comment by 13307130498** [comment]
As a user I want to add a task repeating regularly.

**Comment by 13307130498** [comment]
As a user I want to search tasks with key words.

**Comment by 13307130498** [comment]
As a user I want to view the commands of the software so that I can know how to use it.

**Comment by 13307130498** [comment]
As a user I want to modify the description or date of tasks.

**Comment by 13307130498** [comment]
As a user I want to check the tasks in a proper order so that I could know which one is more urgent.

**Comment by 13307130498** [comment]
As a user I want to use the shorter version of a command so that I could type a task faster.
