### ISSUE TITLE
add command clear

### ISSUE THREAD

**Issue by 13307130498** [cs2103aug2015-f09-1j/main#48]

**Comment by 13307130498** [comment]
Is this finished yet?

**Comment by laddaland** [comment]
this one i implement alr

**Comment by laddaland** [comment]
but got some bug on storage, waiting for yihong to edit .then will push the working code up

**Comment by 13307130498** [comment]
ok..

**Comment by laddaland** [comment]
Sry for the late notice :(

**Comment by 13307130498** [comment]
It's ok.
