### ISSUE TITLE
cannot show the date properly

### ISSUE THREAD

**Issue by 13307130498** [cs2103aug2015-f09-1j/main#54]

**Comment by laddaland** [comment]
ok!. i will look into it :)

**Comment by laddaland** [comment]
problem solved : it is in controller class... haha is your part!..thanks for noticing anyway

**Comment by laddaland** [comment]
i will push the latest code , so that you can read what i change. :)

**Comment by 13307130498** [comment]
I wrote it be for the change of Task...
Thanks:)
