### ISSUE TITLE
@huiying the class name shouldn't be Main , should be Jarvas. And may i know the reason you put the folder name as "sample"?

### ISSUE THREAD

**Issue by laddaland** [cs2103aug2015-f09-1j/main#55]

**Comment by 13307130498** [comment]
When I create a new Project, the sample folder is there, so I just didn't delete it:)

**Comment by laddaland** [comment]
@13307130498 you shouldn't edit the code using other IDE because the structure is totally different.
I have change it back alr. it is my third time change it back alr. haha. .

**Comment by laddaland** [comment]
and I also change change some of the system generate code in fxml. because it is just for the convenience . And lead to errors

**Comment by laddaland** [comment]
try to work on current project and stop moving code from other ide to eclipse. And you should adapt to Eclipse..haha cheers!!!

**Comment by 13307130498** [comment]
>_< Sorry about that

**Comment by laddaland** [comment]
haha.. don't be sorry..just letting you know only.don't worry!! :)
