### ISSUE TITLE
Storage.convertToVector() has bugs

### ISSUE THREAD

**Issue by 13307130498** [cs2103aug2015-f09-1j/main#56]

**Comment by 13307130498** [comment]
test 
Storage storage = new Storage("mytextfile.txt");

**Comment by laddaland** [comment]
i reading storage class, you mean Storage storage = new Storage("mytextfile.txt"); not working?

**Comment by 13307130498** [comment]
yes

**Comment by laddaland** [comment]
ok, i try to solve it.. thanks !!!

**Comment by laddaland** [comment]
oh,,i think what the code mean is to read the task inside "mytextfile.txt"  into our json array.
after that use mytextfile.txt as the for future instead of default one.
which part of it not working?

**Comment by 13307130498** [comment]
just try to run Storage storage = new Storage("mytextfile.txt"); 
Does it work?

**Comment by laddaland** [comment]
oh i see.. it doesn't work..haha

**Comment by laddaland** [comment]
thanks for notify .. i will try to solve for yh

**Comment by laddaland** [comment]
solved it alr. 
if the file is not created, i will show us file missing,
if the file is alr created and with "[]" inside, it will no be error. .
In our case because our mytextfile.txt is empty.

**Comment by 13307130498** [comment]
thanks :)
I'll test it again

**Comment by laddaland** [comment]
no problem :)
i will edit it , if file not exist create file instead.
